INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (1,'Mexico','CDMX','CDMX','Calle Madero',03239,31540);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (2,'Mexico','CDMX','CDMX','Avenida Juárez',91151,41640);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (3,'Mexico','CDMX','CDMX','Paseo de la Reforma',06603,78436);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (4,'Mexico','CDMX','CDMX','Avenida Álvaro Obregón',2,83450);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (5,'Mexico','CDMX','CDMX','Calle Génova',2,39266);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (6,'Mexico','CDMX','CDMX','Avenida Juárez',84569,29020);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (7,'Mexico','CDMX','CDMX','Calle Madero',95631,72089);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (8,'Mexico','CDMX','CDMX','Calle Génova',230,74960);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (9,'Mexico','CDMX','CDMX','Paseo de la Reforma',997,40070);
INSERT INTO Edificio(IdEdificio,Pais,Estado,Ciudad,Calle,Numero,CP) VALUES (10,'Mexico','CDMX','CDMX','Avenida Álvaro Obregón',888,94724);

INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,1,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,2,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,3,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,4,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,5,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,6,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,7,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,8,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,9,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,10,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,11,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,12,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,13,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,14,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,15,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,16,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,17,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,18,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,19,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,20,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,21,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,22,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,23,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,24,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,25,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,26,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,27,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,28,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,29,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,30,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,31,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,32,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,33,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,34,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,35,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,36,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,37,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,38,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,39,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,40,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,41,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,42,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,43,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,44,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,45,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,46,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,47,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,48,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,49,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,50,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,51,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,52,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,53,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,54,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,55,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,56,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,57,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,58,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,59,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,60,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,61,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,62,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,63,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,64,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,65,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,66,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,67,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,68,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,69,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,70,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,71,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,72,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,73,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,74,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,75,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,76,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,77,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,78,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,79,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,80,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (1,81,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (2,82,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (3,83,'Ocupado');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (4,84,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (5,85,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (6,86,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (7,87,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (8,88,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (9,89,'Disponible');
INSERT INTO Piso(IdEdificio,IdPiso,Estatus) VALUES (10,90,'Disponible');

